/**
 * NODE_DEFS — canonical definition of every node type.
 *
 * Each entry:
 *   label   {string}   human-readable name shown in the palette / panel header
 *   icon    {string}   emoji / ASCII icon
 *   color   {string}   hex accent colour
 *   group   {string}   "trigger" | "action" | "integration" | "utility"
 *   fields  {Array}    config fields rendered by ConfigPanel
 *     { k, l, ph, mono?, textarea?, secret?, type?, options? }
 */
export const NODE_DEFS = {
  "trigger.manual":      { label:"Manual Trigger",    icon:"▶",  color:"#059669", group:"trigger",   fields:[] },
  "trigger.webhook":     { label:"Webhook Trigger",   icon:"🔗", color:"#0284c7", group:"trigger",   fields:[{k:"description",l:"Description",ph:"What this webhook receives…"},{k:"secret",l:"HMAC Secret (optional)",ph:"Leave blank to accept any POST",secret:true},{k:"allowed_origins",l:"Allowed Origins (one per line, blank = any)",ph:"https://app.example.com\nhttps://admin.example.com",textarea:true}] },
  "trigger.rss":         { label:"RSS / Atom Feed",   icon:"📡", color:"#ea580c", group:"trigger",   fields:[
    {k:"url",l:"Feed URL",ph:"https://feeds.example.com/rss.xml"},
    {k:"lookback_minutes",l:"Lookback window (minutes, 0 = all)",ph:"60"},
    {k:"filter_expression",l:"Filter expression (use 'entry' dict, optional)",ph:"'python' in entry.get('title','').lower()",mono:true},
    {k:"max_entries",l:"Max entries",ph:"50"},
  ]},
  "trigger.cron":        { label:"Cron Schedule",     icon:"⏰", color:"#7c3aed", group:"trigger",   fields:[{k:"cron",l:"Cron expression",ph:"0 9 * * 1-5"},{k:"timezone",l:"Timezone",ph:"UTC"},{k:"description",l:"Description (optional)",ph:"Weekdays at 9am"}] },
  "action.http_request": { label:"HTTP Request",      icon:"🌐", color:"#0891b2", group:"action",    fields:[{k:"url",l:"URL",ph:"https://api.example.com/data"},{k:"method",l:"Method",ph:"GET",type:"select",options:["GET","POST","PUT","PATCH","DELETE","HEAD"]},{k:"credential",l:"Bearer Credential (name)",ph:"my-api-credential"},{k:"headers_json",l:"Headers (JSON)",ph:'{"Authorization":"Bearer {{token}}"}',mono:true},{k:"body_json",l:"Body (JSON)",ph:'{"key":"{{value}}"}',mono:true,textarea:true},{k:"form_json",l:"Form data (JSON)",ph:'{"field":"value"}',mono:true},{k:"timeout",l:"Timeout (seconds)",ph:"30"},{k:"ignore_errors",l:"Ignore HTTP errors",ph:"false",type:"select",options:["false","true"]}] },
  "action.transform":    { label:"Transform",         icon:"⚙",  color:"#7c3aed", group:"action",    fields:[{k:"expression",l:"Python expression",ph:"{'out': input['value'] * 2}",mono:true,textarea:true}] },
  "action.condition":    { label:"Condition",         icon:"◈",  color:"#d97706", group:"action",    fields:[{k:"expression",l:"Condition (Python bool)",ph:"input.get('status') == 'ok'",mono:true}] },
  "action.filter":       { label:"Filter / Where",    icon:"🔽", color:"#0d9488", group:"action",    fields:[{k:"field",l:"Array field (blank = whole input)",ph:"items"},{k:"expression",l:"Keep condition (use 'item')",ph:"item.get('active') == True",mono:true,textarea:true}] },
  "action.log":          { label:"Log",               icon:"📋", color:"#475569", group:"action",    fields:[{k:"message",l:"Message",ph:"{{input.value}}"}] },
  "action.set_variable": { label:"Set Variable",      icon:"📌", color:"#be185d", group:"action",    fields:[{k:"key",l:"Variable name",ph:"my_var"},{k:"value",l:"Value",ph:"{{input.result}}"}] },
  "action.delay":        { label:"Delay / Wait",      icon:"⏱", color:"#4b5563", group:"action",    fields:[{k:"seconds",l:"Seconds",ph:"5"}] },
  "action.run_script":   { label:"Run Python Script", icon:"🐍", color:"#84cc16", group:"action",    fields:[{k:"script",l:"Python script (assign result)",ph:"# input contains upstream output\nresult = {'doubled': input.get('value',0) * 2}",mono:true,textarea:true}] },
  "action.llm_call":     { label:"LLM Call",          icon:"🤖", color:"#8b5cf6", group:"action",    fields:[{k:"model",l:"Model",ph:"gpt-4o-mini"},{k:"prompt",l:"Prompt",ph:"Summarise this: {{upstream.body}}",textarea:true},{k:"system",l:"System prompt (optional)",ph:"You are a helpful assistant.",textarea:true},{k:"api_key",l:"API Key (blank = env)",ph:"sk-…",secret:true},{k:"api_base",l:"API Base (blank = OpenAI)",ph:"https://api.groq.com/openai/v1"}] },
  "action.wait_for_approval": { label:"Wait for Approval", icon:"🔔", color:"#d97706", group:"action", fields:[
    {k:"approver_email", l:"Approver Email",     ph:"manager@example.com"},
    {k:"subject",        l:"Email Subject",       ph:"Action required: approval needed"},
    {k:"message",        l:"Context / Message",   ph:"Please review and approve this step.\n\nDetails: {{upstream.summary}}", textarea:true},
    {k:"timeout_hours",  l:"Timeout (hours)",     ph:"48"},
  ]},
  "action.send_email":   { label:"Send Email",        icon:"✉",  color:"#0e7490", group:"action",    fields:[{k:"to",l:"To",ph:"user@example.com"},{k:"subject",l:"Subject",ph:"Hello from HiveRunr"},{k:"body",l:"Body",ph:"Hi,\n\nYour task completed.",textarea:true},{k:"credential",l:"SMTP Credential (name)",ph:"my-smtp-server"},{k:"smtp_host",l:"SMTP Host (overrides credential)",ph:"smtp.agentmail.to"},{k:"smtp_user",l:"SMTP User (overrides credential)",ph:"inbox@agentmail.to"},{k:"smtp_pass",l:"SMTP Pass (overrides credential)",ph:"your-api-key",secret:true}] },
  "action.telegram":     { label:"Telegram Message",  icon:"✈",  color:"#0088cc", group:"action",    fields:[{k:"text",l:"Message",ph:"Task done: {{input.result}}",textarea:true},{k:"bot_token",l:"Bot Token (blank = env)",ph:"123456:ABC…",secret:true},{k:"chat_id",l:"Chat ID (blank = env)",ph:"-100123456789"}] },
  "action.loop":         { label:"Loop / For Each",   icon:"🔄", color:"#7e22ce", group:"action",    fields:[{k:"field",l:"Array field (blank = whole input)",ph:"items"},{k:"max_items",l:"Max iterations",ph:"100"}] },
  "action.slack":        { label:"Slack Message",     icon:"💬", color:"#4a154b", group:"action",    fields:[{k:"credential",l:"Slack Credential (name)",ph:"my-slack"},{k:"webhook_url",l:"Webhook URL (overrides credential)",ph:"https://hooks.slack.com/services/...",secret:true},{k:"message",l:"Message",ph:"Flow done: {{upstream.result}}",textarea:true},{k:"channel",l:"Channel (optional)",ph:"#notifications"}] },
  "action.call_graph":   { label:"Call Sub-flow",     icon:"⛓",  color:"#6366f1", group:"action",    fields:[{k:"graph_id",l:"Target Graph ID",ph:"123"},{k:"payload",l:"Payload override (JSON)",ph:'{"key":"{{upstream.value}}"}',textarea:true,mono:true}] },
  "action.ssh":          { label:"SSH Command",       icon:"💻", color:"#0f766e", group:"action",    fields:[{k:"credential",l:"SSH Credential (name)",ph:"my-ssh-server"},{k:"host",l:"Host (overrides credential)",ph:"192.168.1.1"},{k:"port",l:"Port (overrides credential)",ph:"22"},{k:"username",l:"Username (overrides credential)",ph:"admin"},{k:"password",l:"Password (overrides credential)",ph:"••••••••",secret:true},{k:"command",l:"Command",ph:"ls -la /var/log",mono:true,textarea:true}] },
  "action.sftp":         { label:"SFTP / FTP",        icon:"📁", color:"#1d4ed8", group:"action",    fields:[{k:"credential",l:"SFTP Credential (name)",ph:"my-sftp-server"},{k:"protocol",l:"Protocol (overrides credential)",ph:"sftp",type:"select",options:["sftp","ftp"]},{k:"host",l:"Host (overrides credential)",ph:"files.example.com"},{k:"port",l:"Port (overrides credential)",ph:"22 (sftp) · 21 (ftp)"},{k:"username",l:"Username (overrides credential)",ph:"admin"},{k:"password",l:"Password (overrides credential)",ph:"••••••••",secret:true},{k:"operation",l:"Operation",ph:"list",type:"select",options:["list","upload","download","delete","mkdir","rename","exists","stat"]},{k:"remote_path",l:"Remote path",ph:"/uploads/report.csv",mono:true},{k:"recursive",l:"Recursive (list only)",ph:"false",type:"select",options:["false","true"]},{k:"new_path",l:"New path (rename only)",ph:"/uploads/renamed.csv",mono:true},{k:"content",l:"Content (upload only)",ph:"{{upstream.body}}",textarea:true},{k:"timeout",l:"Timeout (seconds)",ph:"30"}] },
  "action.github":       { label:"GitHub",            icon:"🐙", color:"#24292f", group:"integration", fields:[
    {k:"credential",l:"GitHub Credential (name)",ph:"my-github"},
    {k:"token",l:"Token (overrides credential)",ph:"ghp_…",secret:true},
    {k:"action",l:"Action",ph:"list_issues",type:"select",options:["get_repo","list_issues","get_issue","create_issue","close_issue","add_comment","list_commits","list_prs","get_file","create_release"]},
    {k:"owner",l:"Owner",ph:"my-org or username"},
    {k:"repo",l:"Repository",ph:"my-repo"},
    {k:"issue_number",l:"Issue / PR number",ph:"42"},
    {k:"title",l:"Title (create_issue / create_release)",ph:"Bug: something broken"},
    {k:"body",l:"Body / Comment",ph:"Details…",textarea:true},
    {k:"labels",l:"Labels (comma-separated)",ph:"bug,priority"},
    {k:"path",l:"File path (get_file)",ph:"src/main.py"},
    {k:"ref",l:"Branch / tag (get_file / list_commits)",ph:"main"},
    {k:"tag",l:"Tag name (create_release)",ph:"v1.0.0"},
  ]},
  "action.google_sheets":{ label:"Google Sheets",     icon:"📊", color:"#0f9d58", group:"integration", fields:[
    {k:"credential",l:"Google SA Credential (name)",ph:"my-google-sa"},
    {k:"service_account_json",l:"Service Account JSON (overrides credential)",ph:'{"type":"service_account",…}',secret:true,textarea:true,mono:true},
    {k:"action",l:"Action",ph:"read_range",type:"select",options:["read_range","write_range","append_rows","clear_range"]},
    {k:"spreadsheet_id",l:"Spreadsheet ID",ph:"1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms"},
    {k:"range",l:"Range (A1 notation)",ph:"Sheet1!A1:D10"},
    {k:"rows_json",l:"Rows JSON (write / append)",ph:'[["Name","Age"],["Alice",30]]',textarea:true,mono:true},
    {k:"header_row",l:"First row is header? (read_range)",ph:"true"},
  ]},
  "action.notion":       { label:"Notion",            icon:"🗒", color:"#000000", group:"integration", fields:[
    {k:"credential",l:"Notion Credential (name)",ph:"my-notion"},
    {k:"token",l:"Integration Token (overrides credential)",ph:"secret_…",secret:true},
    {k:"action",l:"Action",ph:"query_database",type:"select",options:["query_database","get_page","create_page","update_page","search","append_blocks"]},
    {k:"database_id",l:"Database ID (query_database / create_page)",ph:"abc123…"},
    {k:"page_id",l:"Page ID (get/update/append)",ph:"def456…"},
    {k:"filter_json",l:"Filter JSON (query_database)",ph:'{"property":"Status","select":{"equals":"Done"}}',textarea:true,mono:true},
    {k:"properties_json",l:"Properties JSON (create/update)",ph:'{"Name":{"title":[{"text":{"content":"Hello"}}]}}',textarea:true,mono:true},
    {k:"query",l:"Search query (search)",ph:"Meeting notes"},
    {k:"content",l:"Content text (append_blocks)",ph:"New paragraph text"},
  ]},
  "action.merge":        { label:"Merge / Join",      icon:"⇒",  color:"#0f766e", group:"action", fields:[
    {k:"mode",l:"Mode",ph:"dict",type:"select",options:["dict","all","first"]},
  ]},
  "action.switch":       { label:"Switch / Router",   icon:"⑂",  color:"#b45309", group:"action", fields:[
    {k:"value",l:"Value expression",ph:"input.get('status')",mono:true},
    {k:"cases",l:"Cases (JSON array)",ph:'[{"match":"ok","label":"success"},{"match":"error","label":"failure"}]',mono:true,textarea:true},
  ]},
  "action.aggregate":    { label:"Aggregate",         icon:"⊞",  color:"#0f766e", group:"action", fields:[
    {k:"mode",l:"Mode",ph:"list",type:"select",options:["list","dict","concat"]},
    {k:"field",l:"Extract field from each item (optional)",ph:"result"},
    {k:"separator",l:"Separator (concat mode)",ph:"\\n"},
  ]},
  "action.date":         { label:"Date / Time",       icon:"📅", color:"#0369a1", group:"action", fields:[
    {k:"operation",l:"Operation",ph:"now",type:"select",options:["now","format","parse","add","subtract","diff"]},
    {k:"date",l:"Date / timestamp (blank = now)",ph:"{{upstream.created_at}}"},
    {k:"date2",l:"Second date (diff only)",ph:"{{upstream.updated_at}}"},
    {k:"format",l:"Output format (strftime)",ph:"%Y-%m-%d %H:%M:%S"},
    {k:"amount",l:"Amount (add / subtract)",ph:"1"},
    {k:"unit",l:"Unit (add / subtract)",ph:"days",type:"select",options:["seconds","minutes","hours","days","weeks"]},
  ]},
  "action.discord":      { label:"Discord",           icon:"🎮", color:"#5865f2", group:"action", fields:[
    {k:"credential",l:"Discord Credential (name)",ph:"my-discord"},
    {k:"webhook_url",l:"Webhook URL (overrides credential)",ph:"https://discord.com/api/webhooks/…",secret:true},
    {k:"message",l:"Message",ph:"Flow done: {{upstream.result}}",textarea:true},
    {k:"username",l:"Bot display name (optional)",ph:"HiveRunr"},
    {k:"avatar_url",l:"Avatar URL (optional)",ph:"https://…/icon.png"},
  ]},
  "action.airtable":     { label:"Airtable",          icon:"🟧", color:"#f59e0b", group:"integration", fields:[
    {k:"credential",l:"Airtable Credential (name)",ph:"my-airtable"},
    {k:"api_key",l:"API Key / PAT (overrides credential)",ph:"pat…",secret:true},
    {k:"base_id",l:"Base ID (overrides credential)",ph:"app…",mono:true},
    {k:"table",l:"Table name",ph:"Tasks"},
    {k:"operation",l:"Operation",type:"select",options:["list_records","search","get_record","create_record","update_record","upsert_record","delete_record"]},
    {k:"record_id",l:"Record ID (get / update / delete)",ph:"rec…",mono:true},
    {k:"fields_json",l:'Fields (JSON — create / update / upsert)',ph:'{"Name":"{{input.title}}","Status":"Open"}',textarea:true,mono:true},
    {k:"filter_formula",l:"Filter formula (list / search)",ph:"AND({Status}='Open',{Priority}='High')"},
    {k:"upsert_field",l:"Merge-on field (upsert only)",ph:"Email"},
    {k:"sort_json",l:"Sort (JSON array)",ph:'[{"field":"Name","direction":"asc"}]',mono:true},
    {k:"view",l:"View name (list / search)",ph:"Grid view"},
    {k:"max_records",l:"Max records (list / search)",ph:"100"},
  ]},
  "action.pdf":          { label:"PDF Generate",      icon:"📋", color:"#b91c1c", group:"action", fields:[
    {k:"html",l:"HTML source (supports {{templates}})",ph:"<h1>Report for {{input.name}}</h1><p>Generated: {{input.date}}</p>",textarea:true,mono:true},
    {k:"filename",l:"Filename",ph:"report.pdf"},
    {k:"page_size",l:"Page size",type:"select",options:["a4","letter","legal"]},
    {k:"orientation",l:"Orientation",type:"select",options:["portrait","landscape"]},
  ]},
  "action.redis":        { label:"Redis",             icon:"🟥", color:"#dc2626", group:"integration", fields:[
    {k:"credential",l:"Redis Credential (name)",ph:"my-redis"},
    {k:"url",l:"Redis URL (overrides credential)",ph:"redis://localhost:6379/0",mono:true},
    {k:"operation",l:"Operation",type:"select",options:["get","set","del","exists","incr","decr","expire","ttl","lpush","rpush","lpop","rpop","llen","lrange","sadd","smembers","hset","hget","hgetall","ping"]},
    {k:"key",l:"Key",ph:"myapp:counter",mono:true},
    {k:"value",l:"Value (set / push / sadd / hset)",ph:"{{upstream.result}}"},
    {k:"field",l:"Hash field (hset / hget)",ph:"fieldname"},
    {k:"ttl",l:"TTL seconds (set / expire)",ph:"3600"},
    {k:"count",l:"Amount (incr / decr)",ph:"1"},
    {k:"start",l:"Start index (lrange)",ph:"0"},
    {k:"stop",l:"Stop index (lrange, -1 = end)",ph:"-1"},
  ]},
  "action.graphql":      { label:"GraphQL",           icon:"◈",  color:"#e535ab", group:"integration", fields:[
    {k:"credential",l:"GraphQL Credential (name)",ph:"my-graphql-api"},
    {k:"endpoint",l:"Endpoint URL (overrides credential)",ph:"https://api.example.com/graphql",mono:true},
    {k:"token",l:"Bearer token (overrides credential)",ph:"••••••••",secret:true},
    {k:"query",l:"Query / Mutation",ph:"query { user(id: \"{{input.id}}\") { name email } }",textarea:true,mono:true},
    {k:"variables_json",l:"Variables (JSON)",ph:'{"id":"{{input.id}}"}',textarea:true,mono:true},
    {k:"operation_name",l:"Operation name (optional)",ph:"GetUser"},
    {k:"headers_json",l:"Extra headers (JSON)",ph:'{"X-Custom":"value"}',mono:true},
    {k:"ignore_errors",l:"Ignore GraphQL errors",type:"select",options:["false","true"]},
    {k:"timeout",l:"Timeout (seconds)",ph:"30"},
  ]},
  "action.csv":          { label:"CSV",               icon:"📄", color:"#16a34a", group:"action", fields:[
    {k:"operation",l:"Operation",ph:"parse",type:"select",options:["parse","generate"]},
    {k:"content",l:"CSV content (parse — blank = use input)",ph:"{{upstream.body}}",textarea:true,mono:true},
    {k:"field",l:"Field containing items (generate)",ph:"rows"},
    {k:"delimiter",l:"Delimiter",ph:","},
  ]},
  "trigger.email":       { label:"Email (IMAP)",      icon:"📧", color:"#0891b2", group:"trigger", fields:[
    {k:"credential",l:"IMAP Credential (name)",ph:"my-imap-server"},
    {k:"folder",l:"Folder / mailbox",ph:"INBOX"},
    {k:"search_criteria",l:"IMAP search criteria",ph:"UNSEEN",mono:true},
    {k:"filter_expression",l:"Filter expression (use 'email' dict, optional)",ph:"'urgent' in email.get('subject','').lower()",mono:true},
    {k:"max_messages",l:"Max messages",ph:"10"},
    {k:"mark_read",l:"Mark as read after fetch",ph:"true",type:"select",options:["true","false"]},
  ]},
  "trigger.file_watch":  { label:"File Watch",        icon:"👁", color:"#7c3aed", group:"trigger", fields:[
    {k:"path",l:"Directory path (local or SFTP)",ph:"/data/incoming"},
    {k:"pattern",l:"File pattern (glob)",ph:"*.csv"},
    {k:"lookback_minutes",l:"Lookback window (minutes)",ph:"60"},
    {k:"min_age_seconds",l:"Min age before pickup (seconds)",ph:"5"},
    {k:"min_size_bytes",l:"Min file size (bytes, 0 = any)",ph:"0"},
    {k:"recursive",l:"Recursive scan",ph:"false",type:"select",options:["false","true"]},
    {k:"sftp_credential",l:"SFTP Credential (blank = local)",ph:"my-sftp-server"},
  ]},
  "action.postgres":     { label:"SQL Query",         icon:"🐘", color:"#336791", group:"integration", fields:[
    {k:"credential",l:"DB Credential (name)",ph:"my-postgres"},
    {k:"dsn",l:"DSN / connection string (overrides credential)",ph:"postgresql://user:pass@host:5432/db",mono:true},
    {k:"query",l:"SQL query",ph:"SELECT * FROM users WHERE id = {{input.id}}",textarea:true,mono:true},
    {k:"params",l:"Parameters (JSON array — positional %s)",ph:'["{{input.id}}"]',mono:true},
    {k:"row_limit",l:"Row limit",ph:"100"},
  ]},
  "action.mysql":        { label:"MySQL Query",        icon:"🐬", color:"#00758f", group:"integration", fields:[
    {k:"credential",l:"DB Credential (name)",ph:"my-mysql"},
    {k:"query",l:"SQL query",ph:"SELECT * FROM users WHERE id = %s",textarea:true,mono:true},
    {k:"params",l:"Parameters (JSON array)",ph:'["{{input.id}}"]',mono:true},
    {k:"row_limit",l:"Row limit",ph:"100"},
  ]},
  "action.jira":         { label:"Jira",               icon:"🔵", color:"#0052cc", group:"integration", fields:[
    {k:"credential",l:"Jira Credential (name)",ph:"my-jira"},
    {k:"operation",l:"Operation",type:"select",options:["get-issue","create-issue","update-issue","add-comment","search","get-transitions","transition-issue","delete-issue"]},
    {k:"issue_key",l:"Issue key (get/update/comment/transition/delete)",ph:"PROJ-123",mono:true},
    {k:"jql",l:"JQL query (search)",ph:"project = PROJ AND status = 'To Do' ORDER BY created DESC",textarea:true,mono:true},
    {k:"project_key",l:"Project key (create-issue)",ph:"PROJ"},
    {k:"issue_type",l:"Issue type (create-issue)",ph:"Task"},
    {k:"summary",l:"Summary (create-issue)",ph:"{{input.title}}"},
    {k:"description",l:"Description (create-issue)",ph:"{{input.body}}",textarea:true},
    {k:"priority",l:"Priority (create-issue)",ph:"Medium"},
    {k:"assignee",l:"Assignee email or account ID (create-issue)",ph:"user@example.com"},
    {k:"labels",l:"Labels comma-sep (create-issue)",ph:"backend,bug"},
    {k:"fields",l:"Fields JSON (update-issue)",ph:'{"summary":"New title","priority":{"name":"High"}}',textarea:true,mono:true},
    {k:"comment",l:"Comment text (add-comment / transition-issue)",ph:"{{input.note}}",textarea:true},
    {k:"transition_id",l:"Transition ID (transition-issue)",ph:"21"},
    {k:"fields_return",l:"Fields to return (search, comma-sep)",ph:"summary,status,assignee,priority,issuetype"},
    {k:"max_results",l:"Max results (search)",ph:"50"},
    {k:"extra_fields",l:"Extra fields JSON (create-issue)",ph:'{"customfield_10001":"value"}',mono:true},
  ]},
  "action.s3":           { label:"S3 Storage",        icon:"🪣", color:"#FF9900", group:"integration", fields:[
    {k:"credential",l:"S3 Credential (name)",ph:"my-s3"},
    {k:"operation",l:"Operation",type:"select",options:["get","put","list","delete","presigned_url","head","copy"]},
    {k:"bucket",l:"Bucket",ph:"my-bucket"},
    {k:"key",l:"Key / path",ph:"folder/file.txt",mono:true},
    {k:"content",l:"Content (put only)",ph:"{{upstream.body}}",textarea:true},
    {k:"prefix",l:"Prefix (list only)",ph:"folder/"},
    {k:"source_key",l:"Source key (copy only)",ph:"original/file.txt",mono:true},
    {k:"expires_in",l:"Expires (presigned_url, seconds)",ph:"3600"},
    {k:"max_keys",l:"Max keys (list)",ph:"1000"},
  ]},
  "note":                { label:"Sticky Note",       icon:"📝", color:"#ca8a04", group:"utility",   fields:[{k:"text",l:"Note text",ph:"Document what this part of the flow does…",textarea:true},{k:"colour",l:"Colour",type:"select",options:["amber","blue","green","purple","red","slate"]},{k:"width",l:"Width (px)",ph:"200"},{k:"height",l:"Min height (px)",ph:"100"}] },
};

export const GROUPS = [
  { id: "trigger",     label: "Triggers"     },
  { id: "action",      label: "Actions"      },
  { id: "integration", label: "Integrations" },
  { id: "utility",     label: "Utilities"    },
];
